project:
    waves             : wave1
    machinecount      : 1
machine1:
    machineName       : JBIANCO-LAPTOP
    subnetIDs         : [subnet-XXXXX]
    securitygroupIDs  : [sg-XXXXX]
    instanceType      : t2.micro
    iamRole           : None
    tenancy           : SHARED
    tags              :
       count          : 3
       key1           : Name
       value1         : JBIANCODEV01
       key2           : migrated
       value2         : 'true'
       key3           : environment
       value3         : TEST
